### ISSUE TITLE
Sidebar tabs not clickable

### ISSUE THREAD

**Issue by edduarte** [anakinsk/SafariStand#1]
On Mac OS Sierra (v10.12) and Safari 10.0 (12602.1.50.0.10), tabs are properly shown on the sidebar, and when hovering a sidebar tab's favicon it's replaced by a close icon, as intended. However, clicking on the tab does not show that tab, and clicking the close icon doesn't close the tab. I'm using mySIMBL v.0.3.1 (21), and only have this version of SafariStand installed.

**Comment by edduarte** [comment]
I just found out that sidebar tabs are not draggable either. Personally, dragging isn't as important, but nevertheless I think both clicking and dragging problems are related.

I tried to look at the code, and I suspect that the sidebar-tab selection/click handling is in this method: https://github.com/anakinsk/SafariStand/blob/master/SafariStand/Sidebar/STSidebarCtl.m#L124 . But I might be wrong, since I lack knowledge in Mac OS APIs.

**Comment by anakinsk** [comment]
Partially fixed in 10.0.655, all features of sidebar should be working fine now except drag and drop;

Drag and drop works fine on El Capitan, but not on Sierra. I wasn't able to really understand why, it seems like a tabview component (in which sidebar is currently being injected to) intercepts drag and drop sessions and aborts them cause we are doing something it does not expect :)

I tried to inject a sidebar into NSWindow instead, and received a positive result. However, due to the strongly coupled nature of the code in that module, everything in that sidebar expects a tabview as a parent and it is quite a task to re-write all this.

**Comment by edduarte** [comment]
Wow, that was pretty fast!

Yea, I figured some of the features would be permanently broken now, since
Apple tends gradually close off more and more their APIs in every OS
release. Nevertheless, I'm so glad at least clicking and closing is working
now!

Thank you so much for maintaining the project! I really appreciate it.

PS: I noticed when attempting to review the code that it has a lot of
unused classes, unused variables, and weird indentation, which I bet it
makes maintaining the codebase a pain. If you're working with AppCode, you
should try to run the "Reformat Code" option and use the inspections
feature (
http://stackoverflow.com/questions/30669093/remove-unused-variable-declarations-automatically-android-studio-inteiij)
to fix some of that stuff for you. If not, I could try to fork and PR those
changes, but usually that process changes a lot of lines and makes merging
commits an horrible experience :)

**Comment by edduarte** [comment]
Just tested it and it seems to work perfectly. We should probably rename this issue as "Sidebar tabs not draggable" and leave it open so that people who wanted that feature can find this issue and check your explanation. Or maybe create a new issue with that info and close this one. You decide :)

Thanks again!

**Comment by anakinsk** [comment]
Yep it is probably a great idea to use something that can fix that weird formatting. Good to know that app code can do it. I will try to make that change sometime soon :)

Yep actually if you can derive that dragging issue into a separate one that'd be cool :)

**Comment by edduarte** [comment]
Done and done:
https://github.com/anakinsk/SafariStand/issues/9
