### ISSUE TITLE
"Expand Address Bar Width" not working

### ISSUE THREAD

**Issue by Fofer** [anakinsk/SafariStand#11]
This checkbox, and its associated slider, doesn't appear to have any effect at all.

**Comment by anakinsk** [comment]
hmm it works for me. 

![screen shot 2016-10-20 at 10 39 32 am](https://cloud.githubusercontent.com/assets/5235150/19538652/93afcf8a-96b1-11e6-9d91-d5aa6d729c37.png)

Any other details, like version of safari, os, does it work after safari restart etc :) ?

**Comment by Fofer** [comment]
I've just experimented a bit more and see that it does work for me too.  I just have too many other toolbar icons taking up too much space!

This issue can be closed.
