### ISSUE TITLE
Suppress Tab Bar Width

### ISSUE THREAD

**Issue by sxandy** [anakinsk/SafariStand#12]
Suppress Tab Bar Width not working correct no Label on thirst tab, rearranging tabs also
not working.
Bookmark Icon on Console Panel not visible it is not a big issue 

Thank you for bringing SafariStand to version 10 :)

**Comment by anakinsk** [comment]
Hey could you pls derive bookmark icon into a separate issue?

**Comment by crathecrub** [comment]
@sxandy Please see https://github.com/anakinsk/SafariStand/issues/5

**Comment by Fofer** [comment]
By "bookmark icon" do you mean "favicon?"  Because I am seeing them on the pages listed in my Console Panel.

**Comment by sxandy** [comment]
@Fofer I mean the icon in the toolbar it is not visible.

**Comment by anakinsk** [comment]
Duplicate of https://github.com/anakinsk/SafariStand/issues/5
