### ISSUE TITLE
Installation woes: "Stand" menu not appearing in Safari 10.0/macOS 10.12

### ISSUE THREAD

**Issue by giantspeck** [anakinsk/SafariStand#18]
I'll start by admitting that I haven't used SafariStand in a very long time.  For at least the past three versions of macOS, I've been using Firefox.  When I updated to macOS 10.12, I wanted to give Safari--and thus, SafariStand--another shot.

However, when I install SafariStand and then start Safari, nothing happens.  The following is the process I used to install SafariStand:  

1.  Restart Mac into **Recovery Mode**
2.  Disable **System Integrity Protection**
3.  Restart Mac
4.  Open **mySIMBL** (the most current version, 0.3.1)
5.  Drag and drop the **SafariStand** bundle into **mySIMBL**
6.  Start **Safari**

When I start Safari, the Stand menu does not appear and thus I have no way of configuring SafariStand and have no real idea as to whether it's actually installed properly and working.

Am I missing a step?  Did I forget something crucial and that's why it's not working?

**Comment by Fofer** [comment]
Did you enable SafariStand in mySIMBL by clicking the red dot?  Yellow means it's active for the logged in user only.  Green means it's active for all users.

**Comment by giantspeck** [comment]
I never had to do that because once I dragged and dropped the bundle into mySIMBL, it was active by default.  The dot is green.

![safaristand](https://cloud.githubusercontent.com/assets/8790458/19642279/46000fb2-9980-11e6-9350-91df6e692b47.png)

**Comment by anakinsk** [comment]
Hey did you try the other plugins, do they work for you? If not, try to do another reboot for just in case :)

**Comment by giantspeck** [comment]
cDock worked before I installed SafariStand and continued to work after.  I went ahead and removed FB Eye because I wasn't actually using it and I thought there might have been a conflict, but after rebooting my Mac a second time, SafariStand still doesn't work.  😨

**Comment by giantspeck** [comment]
Okay, this is going to sound weird, but I managed to get it to work.

1.  Navigate to **Applications** folder
2.  Right click **mySIMBL.app** and select **Show Package Contents**
3.  Navigate to /Contents/Frameworks/SIMBLManager.framework/Versions/A/Resources
4.  Double-click **SIMBLAgent.app**
5.  The **Stand** menu appears in Safari.  I didn't have to restart Safari at all.

**Comment by Fofer** [comment]
Great!  You can re-enable System Integrity Protection now.

And maybe report that bug to the developer of mySIMBL?
https://github.com/w0lfschild/mySIMBL

**Comment by anakinsk** [comment]
hmmm weird but I guess it is rather MySIMBL issue then ours. I will close this issue now, glad you got it working in the end.
