### ISSUE TITLE
Is this extension still being maintained?

### ISSUE THREAD

**Issue by crathecrub** [anakinsk/SafariStand#21]
@anakinsk  Really grateful to see Safaristand picked up from Hetima, but since compatibility was made, just wondering if it's still going to be maintained and continue?  How can we support? I'm afraid my coding skills are zero :(

**Comment by anakinsk** [comment]
Hey crathecrub,

Yes it is, but don't expect me to sit and fix ALL those issues anytime soon. It is a big work which requires tons of time, and as you may guess it is something I simply don't have.

I will be fixing the most important things when I have some spare time, but obviously as this is being a free and open source project I cannot make any guarantees except one - favicons will be supported no matter what :)

Also there are two new features coming, tab duplication and ability to choose the behaviour of of that plus button in the address bar.

Cheers

**Comment by crathecrub** [comment]
Thanks anakinsk! Keep the community posted on any help you need! :)
