### ISSUE TITLE
Icon (symbol) "Add in bookmarks"

### ISSUE THREAD

**Issue by staniki** [anakinsk/SafariStand#22]
Hi guys, how into the account of what to add an icon «Add in bookmarks» ?

It isn't added
![0](https://cloud.githubusercontent.com/assets/16809036/20180234/b9602d8c-a76a-11e6-81ca-c18e12dab7a6.png)

It is added
![1](https://cloud.githubusercontent.com/assets/16809036/20180258/d080d0de-a76a-11e6-8f0a-eae2d84ab934.png)

to @anakinsk (it is a little Russian lang)
Привет, Иван, ты сможешь это реализовать? :)

**Comment by staniki** [comment]
isn't added
![v3_0_2x](https://cloud.githubusercontent.com/assets/16809036/20188462/dbc36b7c-a789-11e6-998f-8e4723712de3.png)

addition process
![v3_1_2x](https://cloud.githubusercontent.com/assets/16809036/20188475/e4a1b6ea-a789-11e6-81c3-9c4042267efe.png)

**Comment by anakinsk** [comment]
There's something similar I've done recently, the ability to choose the behaviour of the plus button in the same address bar. Like currently it only adds things into the Reading List, but once that feature is live you will also be able to choose Favorites or Bookmarks Bar.

**Comment by staniki** [comment]
It is very good news :) I look forward :)

P.S. Да это в скече быстренько накидал :)

**Comment by staniki** [comment]
Если нужно, я могу отрисовать все состояния и дать тебе .sketch файл :)

**Comment by anakinsk** [comment]
Спасибо. В том виде в котором ты сделал это конечно был бы идеал, но я чот сомневаюсь что у меня будет когда нибудь время сделать так. 

Я реализовал все в несколько упрощенном порядке, это уже два месяца лежит в репе и ждет пока я сделаю релиз, но чот конец года выдался очень busy и я все никак :)

**Comment by anakinsk** [comment]
Closing this for now as this is partially implemented and waiting for release at the moment.
