### ISSUE TITLE
Double Clicking Titlebar Makes Safari Disappear Forever

### ISSUE THREAD

**Issue by ibrokemypie** [anakinsk/SafariStand#24]
As title says, double clicking the titlebar causes safari to minimise, and then is unable to come back. Only workaround other than quoting that I can find is putting safari in fullscreen mode, but as soon as you leave that it is stuck minimised again.

**Comment by anakinsk** [comment]
Forgive me my ignorance, but I thought there is no more title bar in Safari. Ho can I bring it back to test this?

**Comment by Fofer** [comment]
I think ibrokemypie might be referring to the toolbar?

However, I can't replicate this issue, and am wondering if perhaps he's using some other window manager add-on that's complicating matters?

**Comment by ibrokemypie** [comment]
@Fofer, yep that was it, FullScreenER caused this, not Safaristand.
