### ISSUE TITLE
SafariStand v10.0.665 not working with latest SIMBL/mySIMBL?

### ISSUE THREAD

**Issue by JayBrown** [anakinsk/SafariStand#28]
After updating mySIMBL to v0.4.2, SafariStand stopped working in Safari 10.0.2 on OS X 10.11.6, i.e. the SafariStand menu does not show, and all functionality is disabled. Anyone else experiencing this?

**Comment by JayBrown** [comment]
PS: same after reboot; SIMBL plugin cDock is working fine, so the error seems to be with SafariStand.

**Comment by JayBrown** [comment]
**Solved:** it was not a SafariStand error, but a SIMBL thing. The following shell command corrected the problem, at least for the current session: `osascript -e "tell application \"Safari\" to inject SIMBL"`

**Comment by anakinsk** [comment]
Thanks JayBrown
