### ISSUE TITLE
Possible to use it when SIP is enabled?

### ISSUE THREAD

**Issue by Askern** [anakinsk/SafariStand#29]
Hello,

is there any way in Safari 10 to use Safaristand with SIP (System Integrated Protection) enabled again, after disabling it to it install MYSIMBL and Safaristand? I tried this but Safaristand only works for me, when SIP is disabled.

I would like to be able to enable my SIP again while still being able to use Safaristand. E.g. Afloat works for me for third party apps while SIP is enabled.

Thank you!

**Comment by Fofer** [comment]
Yes, I only needed to disable SIP temporarily for MySIMBL and SafariStand installation.  Once they were installed, I was able to re-enable SIP, and SafariStand still works, even after many reboots.

**Comment by Askern** [comment]
Actually this is not possible for me. Safari stand works for me in SIP disabled mode only. When I enable SIP it stops to work.

**Comment by Askern** [comment]
@Fofer : Are you using OS X Sierra? I am till on El Cap

**Comment by Fofer** [comment]
I am on Sierra now, yes. But I was still able to run the previous version
of SafariStand on El Capitan, also with SIP enabled.

**Comment by Askern** [comment]
@Fofer : Yes I also was able to use Safaristand on my El Capitan with Safari 9, while SIP being disabled. The Safaristand was from hetima back then. Since installing Safari 10, and mysimbl  + Safaristand from ankinsk i can't use Safaristand while SIP is enabled.

I think I have to move to Sierra soon and I hope that I will be able to use Safaristand while SIP is enabled.  I just don't want to disable my SIP for all the time.

**Comment by Askern** [comment]
I found it out: Under OS X Sierra and Safari 10 it is possible to enable SIP again and to use Safaristand. In OS X El Cap under Safari 10 it is not possible to possible to use Safaristand after enabling SIP again. Thank you all for your help!
