### ISSUE TITLE
SafariStand having no effect on Safari 10 + macOS Sierra

### ISSUE THREAD

**Issue by TomFrost** [anakinsk/SafariStand#3]
This is working for others, so I'm betting I've done something wrong-- here's what I did:

1. Rebooted into Recovery Mode, disabled system integrity protection
2. Installed mySIMBL 0.3.1
3. Dropped in SafariStand ![Screenshot](http://i.tomfro.st/YCvD6Q.png)
4. Launched Safari, opened and pinned some tabs ![Screenshot 2](http://i.tomfro.st/v1AvzU.png)
5. Rebooted and tried Safari again, still no dice.

Did I miss something here?

**Edit:** There is also no effect after removing the com.apple.quarantine extended attribute with `xattr -rc <bundle path>`, or from moving this to the user-level library folder.

**Comment by anakinsk** [comment]
Hey dumb question, but still - did you enable a checkbox in the stand settings? (And are you actually able to see Stand menu in Safari?

**Comment by TomFrost** [comment]
...Not a dumb question at all! I didn't even see the Stand menu. Everything's great now, and I feel a little silly ;-)

**Comment by TomFrost** [comment]
(Also, thanks again for updating this! I've never used SafariStand before now, but this is fantastic.)
