### ISSUE TITLE
Favicon on pinned tab

### ISSUE THREAD

**Issue by jkdufair** [anakinsk/SafariStand#30]
Thanks for making this work with sierra! Would it be possible to show the favicon on a pinned tab? They are working great for non-pinned tabs, but the pinned tabs just show a letter, like without SafariStand.

I'm a developer, so I'm also willing to do this myself if you might have a sec to provide a general approach to solving this. I'll put together a pull request if you like.

**Comment by punch1982** [comment]
I'd love to see this too - did you gain any traction?

**Comment by anakinsk** [comment]
I will close this one as a duplicate of https://github.com/anakinsk/SafariStand/issues/40 (even tho this one was created earlier, I just already put a reply and tags on the other one).
