### ISSUE TITLE
Total meltdown on Safari 10 + Yosemite

### ISSUE THREAD

**Issue by Section25** [anakinsk/SafariStand#31]
I would love to break this down into a number of distinct issues but I have no idea where one ended and another began.

I have been holding out on upgrading to Safari 10 for a number of reasons, one being my addiction to SafariStand so after reading about this development, I took cautious steps to proceed. I created a new partition on one of my drives and installed El Capitan (for other reasons, I'm sticking to Yosemite on my main drive) and then SIMBL and SafariStand and all seemed okay so I installed SafariStand on the Yosemite drive and all was not okay.

One of my main gripes with Safari is the ridiculous tabs so I enabled Suppress Tab Bar Width which seemed to work until I tried opening a web page. There was no title on the tab nor a favicon (also enabled). When I clicked the tab bar or the + icon, nothing seemed to happen but I discovered that there were 'tabs' in the sidebar if I enabled it but when I selected one, there was nothing on the page. After a couple of clicks, the Safari window disappeared altogether. Safari could be selected in the Dock and be the frontmost application but there was no window - which Safari usually creates when selected in the Dock. I selected cmd-N and a window appeared which was about 1000px x 600px at the bottom left of my screen. I could move it but if I tried to resize it, the window itself stayed the same size but the frame grew. I attempted disabling my preferences and made several attempts to access a web page but after having to restart Safari a dozen or more times because it kept crashing, I gave up.

I'm afraid I cannot provide any more information as I restored my system from the last Time Machine backup and I'm back to Safari 9.

The reason I I'm avoiding El Capitan (unrelated to SafariStand) may be resolved so I may take another plunge when I have time to risk having to do another Time Machine restore.

Sorry I couldn't nail it down to a single issue as Safari was completely unusable.

**Comment by Section25** [comment]
I just installed El Capitan and all the problems experienced in my post above seem to be gone - so they look like they are Yosemite related.

**Comment by antgeth** [comment]
just piping up to say that i hope some progress can be made towards getting this working on yosemite.  i am unwilling to update beyond 10.10 for now (for various reasons), but would really, really love to have safaristand functionality back

**Comment by anakinsk** [comment]
Thanks for your input guys, I will attach this to the original issue about Yosemite support. 
https://github.com/anakinsk/SafariStand/issues/4
