### ISSUE TITLE
Hide Tabbar not working

### ISSUE THREAD

**Issue by daven1985** [anakinsk/SafariStand#33]
Afternoon,

When select "Hide tabbar" does nothing. Can this be fixed?

Cheers.

**Comment by daven1985** [comment]
Just discovered today, if you hide the sidebar and then re-enable it the tabbar does disappear. However as soon as you open a new tab it re-appears.

Thought it might help!

**Comment by skinetserver** [comment]
I am also experiencing this issue. The new tab request seems to be overriding the hide Tabbar.

**Comment by anakinsk** [comment]
Duplicate of https://github.com/anakinsk/SafariStand/issues/10
