### ISSUE TITLE
Weird tab switching / page loading issue

### ISSUE THREAD

**Issue by Section25** [anakinsk/SafariStand#34]
I am in the habit of 'watching' YouTube videos in the background whilst sometimes either reading related webpages or fact checking. Because of this, I have noticed a weird problem which definitely did not occur on previous versions of SafariStand; i.e. that If, say, I am watching a YouTube video (it could be any web page), I open a new tab and start loading a page then reselect the YouTube tab, the page which was loading also opens on the YouTube tab and I end up with two identical tabs.

I only use YouTube as an example because it was by losing the video I was watching that I noticed it happening but it happens with all pages; e.g. a page, say, news site A, could be opening slowly so I open a new tab and go to news site B, as it is loading, I check the first tab and instead of news site B, it loads news site A.

It only seems to happen if the tab is actively doing something such as loading or playing media and it does not happen consistently - I tried to replicate it a few times to describe it properly but it didn't happen every time. Quite frustrating.

**Comment by anakinsk** [comment]
Does that occur without Safari Stand?

**Comment by anakinsk** [comment]
No reply, no confirmation from the other users - closing until more information is provided.
