### ISSUE TITLE
Right-click on Web Inspector makes Safari crash

### ISSUE THREAD

**Issue by kinoute** [anakinsk/SafariStand#36]
Hello,

I'm using SafariStand 10.0.665 with MySIMBL and I get an error when using it on my Mac Mini 2009, running El Capitan 10.11.6 (15G1217) with Safari 10.0.3 (11602.4.8.0.1). This is not a new error, I have it for some time and it's not related to the recent updates of Safari/OS X.

When I open Web Inspector, go to the "Elements" tab, and right-click on the code to, for example, copy it, Safari crashes/closes instantly. If I disable SafariStand, no crash & I see the menu as expected:

![capture d ecran 2017-01-29 a 17 29 21](https://cloud.githubusercontent.com/assets/623763/22405799/84f26c32-e648-11e6-9ac2-bd67a7ccdce8.png)

Here is the crash report of Safari when using SafariStand: https://gist.github.com/kinoute/24d9359267d1faecbfde8d85710a7ea6

Regards,

Yann

**Comment by bertobox** [comment]
This has happened to me too! I’m using SafariStand 10.0.665 on a Retina 15" MacBook (late 2013) running Mac OS X El Capitan 10.11.6 and Safari version 10.0.3 (11602.4.8.0.1)

**Comment by anakinsk** [comment]
Fixed. Will be included into the upcoming update;

**Comment by anakinsk** [comment]
Fixed in 10.1.1 release.
