### ISSUE TITLE
Can your new fork support Safari 10 on Yosemite?

### ISSUE THREAD

**Issue by raugust7** [anakinsk/SafariStand#4]
For a number of reasons, I still need to run on MacOS 10.10 Yosemite.  Is there any chance that your new fork of SafariStand can have a version to support Safari 10 on Yosemite?

Your current release fails to load as soon as any options, such as those for tab width and favicon on tabs are enabled.

Many thanks.

**Comment by anakinsk** [comment]
I can look into this. A bit of complexity here is that I don't have yosemite, but I guess I can utilise some virtual machine. No promises made tho, if it's easy to fix, I will fix it. If not, we'll see how popular this request is and then make a decision on the priority :)

**Comment by zionkrl** [comment]
Hello. Yes please, SafariStand for Yosemite and Safari 10!

Thank you.

**Comment by Gavrrik** [comment]
I would also love to have my favicon back, please make SafariStand support Safari 10 on Yosemite10.10.

Thanks.

**Comment by antgeth** [comment]
hear hear! would desperately love this.  i'm currently trying to use it anyway, but it is quite buggy.

**Comment by anakinsk** [comment]
Yosemite support added in version 10.1.2

**Comment by antgeth** [comment]
thank you so much, it's hugely appreciated!
