### ISSUE TITLE
SafariStand injects in 10.12.6 but does not show favicons in the tab bar

### ISSUE THREAD

**Issue by sidpagariya** [anakinsk/SafariStand#43]
I installed SafariStand fresh but don't seem to get the favicons working...
Could you please help me fix this?

Thanks,
Sid.
<img width="1280" alt="screen shot 2017-07-12 at 3 01 37 pm" src="https://user-images.githubusercontent.com/10685754/28135123-27b998f0-6713-11e7-98d1-f2922b7900ed.png">

**Comment by anakinsk** [comment]
Okay, thanks for this. 

Good to see that Stand is at least loaded successfully, which means this issue is fixable.

However as I don't have a spare computer to install a beta on it, this may not get fixed until it goes to the release. Or may be if I am lucky enough I will find some time to put it into the VM. We'll see.

**Comment by trwrt** [comment]
Now that 10.12.6 is released, is it safe to install it?  I don't want to lose my favicons.

**Comment by anakinsk** [comment]
@trwrt no, I still haven't got a chance to try it, but according to @sidpagariya favicons do not work. So better wait a little, I will try to take a look into it soon.

**Comment by anakinsk** [comment]
Favicons on tabs work for me on Sierra 10.12.6 and SafariStand 10.1.2.

**Comment by anakinsk** [comment]
![screen shot 2017-08-01 at 3 41 38 am](https://user-images.githubusercontent.com/5235150/28821851-30e539cc-770b-11e7-8028-d4a72b66de47.png)

**Comment by anakinsk** [comment]
And they also work for me with SafariStand 10.1.1. Not sure if they changed anything since that beta that you were on @sidpagariya, but try release version and let me know if it works?

Closing this for now.

**Comment by sidpagariya** [comment]
Hey guys, sorry, I didn't get a chance to look at the public 10.12.6... let me double check...and I will get back to you very soon
Thanks!

**Comment by sidpagariya** [comment]
Thanks for the update...it seems to work perfectly now...
@anakinsk Thanks so much for keeping this project alive!

Sid.

**Comment by sidpagariya** [comment]
Looks like I get an error in 10.12.6:
```
Failed to load the SafariStand plugin.
*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]
```

**Comment by anakinsk** [comment]
I thought you just said it was working perfectly :-D

Hey do you wanna create a separate issue for this specifying if that happens every time, when does it happen (on launch, some other time), and probably providing a screenshot?

**Comment by trwrt** [comment]
I went ahead with the 10.12.6 update and SafariStand is still working for me, both 10.1.1 and then 10.1.2 after it prompted me to update.

**Comment by sidpagariya** [comment]
Oops, @anakinsk and @trwrt guess what? I was dumb enough to update to Safari 11.0 early preview. I am screwed. I will have to re-download Safari...

Thanks!
Sid.
