### ISSUE TITLE
I'm getting an error when trying to install simbl

### ISSUE THREAD

**Issue by Ldubya83** [anakinsk/SafariStand#45]
I'm getting an error when trying to install simbl. Please take a look at screenshots
![screen shot 2017-07-19 at 7 25 16 pm](https://user-images.githubusercontent.com/30271462/28394004-323c61ae-6cb8-11e7-95c7-e91000aebeac.png)
![screen shot 2017-07-19 at 7 23 57 pm](https://user-images.githubusercontent.com/30271462/28394003-323bc49c-6cb8-11e7-8da8-d73e319662ca.png)

**Comment by anakinsk** [comment]
Hey just FYI this project is about Safari Stand, not SIMBL.

SIMBL homepage is here: https://github.com/w0lfschild/mySIMBL

P.S. However looking at your screenshot I see that you probably wanna check if you system integrity protection is really disabled.

**Comment by anakinsk** [comment]
Closing this, as we do not provide support over mySIMBL here.
