### ISSUE TITLE
High Sierra and Safari 11 Support

### ISSUE THREAD

**Issue by anakinsk** [anakinsk/SafariStand#47]
Users report that tabs feature is not working on Safari 11 in the 10.13 Beta. However, the favicons do work in both the bookmarks and address bars.

**Comment by ilovesafaristand** [comment]
Is everything ok with Safaristand for the High Sierra update? Anything you need? @anakinsk

**Comment by jason-hub** [comment]
I just installed on Safari 11 (Sierra 10.12.6).  The "Stand" menu appears, but the following settings have no effect: 

"Show Icon in Tab Bar"

The icons DO display in the bookmarks sidebar, but the tab bar is much more important.

**Comment by drewauff** [comment]
Can confirm that "Show Icon in Tab Bar" does not work.

Also, everything else seems to work just fine.

**Comment by anakinsk** [comment]
Implemented in 11.0
