### ISSUE TITLE
FINALLY! www.faviconographer.com

### ISSUE THREAD

**Issue by Askern** [anakinsk/SafariStand#54]
Finally Favicons without a "hack" or disabling SIP or any other stuff. JUST installing a program and there you go! Easy installing and working guaranteed. When a wish becomes true! Also works in High Sierra and at least El Capitan is needed. Best wishes!!

https://faviconographer.com

**Comment by staniki** [comment]
you stupid? these are absolutely different technologies

**Comment by staniki** [comment]
for example it will not be suitable for the Russian Internet

**Comment by JayBrown** [comment]
There is no Russian internet. There's just the internet. As for Faviconographer: it's a great app, definitely… I prefer the SafariStand injection method, but SafariStand is dead as a doornail, so the overlay method has to do.

**Comment by staniki** [comment]
no Russian internet? :)) haha, ok :)

**Comment by JayBrown** [comment]
Precisely.

**Comment by staniki** [comment]
SafariStand is not dead while there are such people as @anakinsk

**Comment by staniki** [comment]
@anakinsk Вань, мне кажется немцы пытаются тут пиарить свою поделку :))

**Comment by JayBrown** [comment]
Yeah, hacking/patching/replacing /Applications/Safari.app using some old version… you're grasping at straws. Really, you are. If you can't do better, I'll stick with saying that SafariStand is dead as a doornail. Default Folder X is using the same method as Faviconographer, now that injection is blocked by macOS. That's a German software, too. Oh wait… it isn't.

**Comment by anakinsk** [comment]
Hey @JayBrown, you can also go fuck yourself mate. This is a hobby project done in my own spare time. I don't owe you anything and I personally don't care what you use. You wanna switch to some other software? go for it, you have my blessing. Just stop posting irrelevant bullshit here please.
