### ISSUE TITLE
Failed to load SafariStand (v11, High Sierra)

### ISSUE THREAD

**Issue by umputun** [anakinsk/SafariStand#56]
MySimbl v 0.5.3 (29), SafariStand 11.0

![1ds3v-201710-08133333-n5por](https://user-images.githubusercontent.com/535880/31319692-9f8b96c6-ac2d-11e7-9979-32e854a3438b.png)

![bg9nz-201710-08133629-03a1m](https://user-images.githubusercontent.com/535880/31319697-b28b983e-ac2d-11e7-860a-d3ad1575cf8d.png)

**Comment by umputun** [comment]
fyi: it happens on both of my macs

**Comment by umputun** [comment]
nm, my bad. After installation or SafariStand I've missed patching step

**Comment by anakinsk** [comment]
if you didn't install the patcher how the heck did the stand get through the library validation?? 🤔🤔

Was that new Safari Stand installation or did you have it before upgrading to High Sierra?

**Comment by umputun** [comment]
I had SafariStand before. All I did - downloaded latest safari stand, latest MySimbl, removed old SafariStand and installed the latest. After this error message Safari actually added "Stand" to top menu but nothing else worked.

**Comment by anakinsk** [comment]
and then you patched it again and it started working right?

**Comment by umputun** [comment]
correct
