### ISSUE TITLE
Sierra:  Undeletable tab appears after pinning a tab

### ISSUE THREAD

**Issue by jason-hub** [anakinsk/SafariStand#58]
On Sierra, when I "pin" a tab (either by reducing the tab's size or by using "right-click"), a new, separate, undeletable tab gets created.  When I hover on that tab, the little "x" does not appear.  In fact, the tab is entirely unresponsive.  The only way to get rid of it is to detach all OTHER tabs and then close the entire browser window once the undeletable tab is isolated.

**Comment by anakinsk** [comment]
Try to disable Safari Stand and see if that fixes your issue? Wondering if that is actually our bug or not.

**Comment by anakinsk** [comment]
No response, no confirmation from the other users thus this one is now closed until more information is provided.
