### ISSUE TITLE
Bookmark add problem

### ISSUE THREAD

**Issue by J-charles-C** [anakinsk/SafariStand#6]
,

I think there are a little bug on Add Bookmark (Ctrl D). There are only one choice to "favorite ", not to normal bookmark.

When you add a bookmark, you can't choice where it save it in bar.

Sorry for my bas english.

Jc

**Comment by anakinsk** [comment]
If you open default safari sidebar, are you able to see your bookmark folder?

Also try to disable SafariStand in SIMBL and see if you still can reproduce the issue. That doesn't sound like a SafariStand issue if you ask me... But let's double check :)

**Comment by J-charles-C** [comment]
I,

When i disable safari stand, there are the same bug. It's a SaFari 10 bug.

regards

Jc

**Comment by anakinsk** [comment]
Ok so it is not SafariStand issue. Closed then :)
