### ISSUE TITLE
SafariStand 11.0.0 doesn't work ( tab favicons) on macOS Sierra && High Sierra  

### ISSUE THREAD

**Issue by letItGo0** [anakinsk/SafariStand#62]
Favicons not appearing in tabs

![1508206433752](https://user-images.githubusercontent.com/26651371/31643607-20680642-b324-11e7-832f-61771ec10a4e.jpg)

**Comment by GodBlesses** [comment]
@letItGo0 I see tab and sidebar favicon icons on my machine running 10.13 (Supplemental Update) with the same version of SafariStand and the same version of Safari as shown in your posted screenshot.  Perhaps your config needs modifying.  Did you install the patch script that I have linked to below from anakinsk's main SafariStand page?  (SIP need to be disabled on your system prior to installing the script.  If you need more instructions then I might be able to help.)

https://github.com/anakinsk/SafariStand/files/911989/Safari.Stand.Patcher.pkg.zip

**Comment by letItGo0** [comment]
@GodBlesses thank you  for your advice, I'm using the latest version of the plugin , everything is ok except tab favicons . it worked very well untill safari version update to 11 ,so I updated the plugin on my mac,and it not work ,  then i updated OS to High Sierra,However, it is still useless..   could you please post your screenshot as I do ? I don't know what the reason is ~

thanks a lot !

**Comment by anakinsk** [comment]
@letItGo0 did you actually install the patcher? There were reports that indicate that in some cases the patch needs to be re-applied after the update.

**Comment by letItGo0** [comment]
@anakinsk  I disable SIP & install the patcher again ,it doesn't work, then i reinstall SIMBL ,also not work

**Comment by GodBlesses** [comment]
Here is a screenshot of my configuration:
![screen shot 2017-10-22 at 02 51 02](https://user-images.githubusercontent.com/32898257/31860729-dbdabd4a-b6d3-11e7-928e-a612469f1da6.png)

Edit: Also you might want to check in Activity Monitor to see if both "mySIMBLAgent" and "SIMBLAgent" are running on your system.  I am not sure if both are needed but both are running on my machine and I have not had a problem with SafariStand favicons showing up.

Perhaps one of your versions of software is different than what is in my screenshot above.

Edit 2: I also though it might help to let you know that my version of mySIMBLAgent is 6.0 as indicated in the Info.plist file in the "/Applications/mySIMBL.app/Contents/Library/LoginItems/mySIMBLAgent.app/Contents" directory on my hard drive.

**Comment by letItGo0** [comment]
![1508809043909](https://user-images.githubusercontent.com/26651371/31920967-0d9869c8-b89f-11e7-8172-f74f2b421275.jpg)
I did not do anything, and it's working today...

**Comment by anakinsk** [comment]
Finally Safari Stand's started fixing bugs itself! 😀😀

**Comment by letItGo0** [comment]
@anakinsk  I think the reason is that I use the vpn network!!!!

 i can't visit some website like google because of  [GFW(Great Firewall of china)](https://en.wikipedia.org/wiki/Great_Firewall) ;   so i use vpn to visit some website ,SafariStand was working the next day , this happens on my imac and macbook pro ,whether there will be some programs will automatically upgrade about safaristand??

**Comment by anakinsk** [comment]
ah okay. So currently Safari Stand uses google to fetch favicon for each particular website. If google is blocked by GFW, then the favicon request will fail and there will be no favicon displayed in tab bar. 

Also not sure what GFW returns back when it blocks the request, because if it returns some rubbish instead of simply dropping it, the request would be cached and even when you switch to vpn that cache will still be there until you restart you browser. 

Hope that makes sense.

**Comment by letItGo0** [comment]
yes it is , when i close vpn the favicon disappears, when i open vpn the favicon come back.
