### ISSUE TITLE
Sidebar Reordering Of Tabs -- Feature Request

### ISSUE THREAD

**Issue by GodBlesses** [anakinsk/SafariStand#63]
I thought it would be great if SafariStand allowed users to reorder tabs within SafariStand's Sidebar since it is a lot more convenient and clean than reordering on the Safari window Tab Bar or from SafariStand's Console Panel.  It would take less steps and would enhance the workflow since the Sidebar doesn't use much space and stays on the side and out of the way.  What also also makes this feature desirable is the fact that the Sidebar only displays the tabs of a current window where as in the Console Panel a user has to find the area that pertains to the window they are interested in modifying prior to reordering the tabs.  Adding a standard keyboard shortcut for access to the Sidebar would likely be beneficial too.

I'd like to note that I am not desiring dragging anything out of the Sidebar--the reordering would be done within it.  I'm not sure if this was the issue #9 was referring to or not but if dragging items out of the Sidebar was the problem and this feature is easily implemented then please consider adding it.

Thank you @anakinsk for your work keeping the SafariStand project going.

**Comment by anakinsk** [comment]
Hi @GodBlesses, yes that issue #9 is exactly what you described here. 

As I mentioned in this comment here: https://github.com/anakinsk/SafariStand/issues/1#issuecomment-253959667

> Drag and drop works fine on El Capitan, but not on Sierra. I wasn't able to really understand why, it seems like a tabview component (in which sidebar is currently being injected to) intercepts drag and drop sessions and aborts them cause we are doing something it does not expect :)
> 
> I tried to inject the sidebar into NSWindow instead, and received a positive result. However, due to the strongly coupled nature of the code in that module, everything in that sidebar expects a tabview as a parent and it is quite a task to re-write all this.

I have no plans for this at the moment, I just simply don't have time for everything \

**Comment by anakinsk** [comment]
Closed as duplicated of #9

**Comment by GodBlesses** [comment]
Thank you @anakinsk for letting me know.
