### ISSUE TITLE
Safari 11.0.1 support

### ISSUE THREAD

**Issue by levifig** [anakinsk/SafariStand#66]
It's that time again: Safari 11.0.1 has been released, and we're all anxiously waiting for SafariStand support… :)

**Comment by anakinsk** [comment]
Don't tell me that it broke again ☹️

Can you provide the screenshots and stuff, like what doesn't work, do you see the menu stand, what OS are you on etc

**Comment by levifig** [comment]
It might just need a bump in the version number (maybe?). No Stand menu, no favicons, etc… As far as I can tell, it's simply not being loaded. :)

**Comment by anakinsk** [comment]
Ok did you try to re-apply the patch? Cause that is something you need to do every time after safari gets updated.

**Comment by levifig** [comment]
Aww man, now I feel bad! That was it!!! Re-patching fixed it, and Stand is back! <3 Sorry for taking your time… 😬
