### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by BigMacOS** [anakinsk/SafariStand#67]
I'm trying to update extensions; 3rd party from the apple gallery and stuff like 1passs the and getting 
“Safari can’t install this extension”

after troubleshooting it, I believe it may be because of the safari stand patch referencing an older version of safari. Has anyone experienced the same? 

You can see if you have any extensions to update by **unticking** 
safari >preferences >extentions> auto update OFF and see if you have updates. Try to update them and you should see an error.
Or
try to install any extension from https://safari-extensions.apple.com

I'm curious if this is just Safaristand as i've tried everything else.

@anakinsk

**Comment by staniki** [comment]
Да, подтверждаю ошибку, расширения не устанавливаются. Случается это после того как применяешь патч на версию Safari 11.0.2. Кстати говоря, на более ранней версии сафари я устанавливал SafariStand с патчем естественно, так вот, после обновления на 11.0.2 через AppStore, SafariStand продолжал работать, а Safari в эбаут показывал текущую версию, то есть 11.0.2. Жаль я не успел сделать скриншот и переустановил систему, теперь не могу ставить экстеншоны. Вань, посмотри пожалуйста :) И по возможности посмотри что там с разрешением фавиконов, на ретине прям видно что оно у них маленькое :)

**Comment by staniki** [comment]
@anakinsk Я конечно не разбираюсь, но может можно взять файл после того как человек обновился до 11.0.2 с установленным SafariStand и прикрутить его к патчу? Что бы работали экстеншены и в эбаут показывало 11.0.2

**Comment by staniki** [comment]
@anakinsk Поставил еще раз начисто 10.13.2 с Safari 11.0.2, патч не применял и... SafariStand заработал :) Расширения естественно устанавливаются. По видимому аппле убрали защиту? :)

**Comment by staniki** [comment]
<img width="940" alt="2017-12-24 16 27 32" src="https://user-images.githubusercontent.com/16809036/34326838-62f87a7c-e8c7-11e7-9976-cff5560b3812.png">

**Comment by anakinsk** [comment]
@staniki ты знаешь я тоже наблюдал такое у себя, но потом после какого то апдейта сафари перестал инжектиться, и даже копия сафари не помогла. Я не совсем уверен в том, что это было. Можешь подтвердить что после установки всех последних обновлений ты все еще можешь юзать сафари стенд без патча?

**Comment by staniki** [comment]
@anakinsk Да Вань подтверждаю, накатил все последние апдейты из аппстора, версия macos 10.13.2, версия Safari 11.0.2. Сафари стенд инжектится :) 
Вот только бы поправить баг при котором фавикон остается сайта с которого перешел (это хорошо видно когда гуглишь, переходишь из гугла на сайт, и на вкладке показывается все еще фавикон гугла) и поправить разрешение самих фавиконов (для ретины) :)

**Comment by anakinsk** [comment]
It seems that Library Validation is disabled in High Sierra starting 10.13.2+ so it is not necessary to use installer for Safari Stand to work, at least for now. 

I also wasn't able to reproduce this, even with the patch safari installs extensions just fine...

**Comment by anakinsk** [comment]
Unfortunately library validation is back in 10.13.4, so using the patcher is now a requirement yet again. 

Closing this as I can't reproduce it. Please re-open if you are continuing to face this issue.
