### ISSUE TITLE
High Energy Usage

### ISSUE THREAD

**Issue by cooperred** [anakinsk/SafariStand#69]
My average energy impact is insanely high for Safari, 200+. I think I've narrowed it down to Safari Stand. Anyone else have this issue?

**Comment by ivanfaiustovkiwibank** [comment]
How did you narrow it down to Safari Stand exactly? Could you please elaborate :)

**Comment by anakinsk** [comment]
How did you narrow it down to Safari Stand exactly? Could you please elaborate :)

**Comment by anakinsk** [comment]
This one is closed. Unable to reproduce.
