### ISSUE TITLE
10.13.3 - is safaristand working?

### ISSUE THREAD

**Issue by BigMacOS** [anakinsk/SafariStand#73]
Is this working for anyone before I update? 
I see a favicongrapher alternative app for Safari that is updated on a regular basis. Please don't let me jump ship!

**Comment by anakinsk** [comment]
Please go ahead with the alternative and don't bother me with such threats ever again thank you.

**Comment by anakinsk** [comment]
And yes, 10.13.3 is working fine with Safari Stand, at least for me.

**Comment by BigMacOS** [comment]
My username I don't think is working correctly.
Very sorry you feel 'threatened'. Please check my posts stating how much money I've been wanting to offer to donate to develop safaristand. Some communication would be nice such as updates, compatibility, roadmaps, etc don't you think?

**Comment by J-charles-C** [comment]
Anakinsk, thanks for your job.

regards.

**Comment by anakinsk** [comment]
@ilovesafaristand My only "promise" is that I will try to continue supporting favicons feature as much further as possible. I personally don't use any other SafariStand features and this is why they are of lesser priority to me. 

I think I already stated my position around donating, considering the fact that Apple can shut us down at any time by simply making our launcher from Safari 10 incompatible with the current version, it will be unfair to collect any money from you guys knowing that at any time, even tomorrow, Safari Stand can simply disappear as a thing.

I communicate when I can, but unfortunately don't have capacity to work on this project on daily basis.
