### ISSUE TITLE
10.13.4 Beta (17E150g) fail

### ISSUE THREAD

**Issue by russelgal** [anakinsk/SafariStand#74]
![monosnap 2018-02-10 13-56-12](https://user-images.githubusercontent.com/3201077/36060384-4ff3173e-0e6a-11e8-926e-5e0e0a5ad69a.png)

**Comment by BigMacOS** [comment]
Is this working in the 10.13.4 final? 
@anakinsk any news for those waiting to update? :)

**Comment by TarkM** [comment]
Well for everyone using SafariStand:

It's working probably on the lastest AppleUpdate (OSX 10.13.4 / Safari Version 10.0.1 (12602.2.14.0.7) if you just

Reanable SIP
Run the Safari Stand Patcher
Reinstall Safari Stand

an enjoy!

Happyy Easter 🥚and many Thanks to anakinsk to make all these happen 👍
