### ISSUE TITLE
not an issue. SS works without patcher in Safari 11.1.1

### ISSUE THREAD

**Issue by citovsky** [anakinsk/SafariStand#77]
SS 11 now works without the patcher after 10.13.5 update under Safari 11.1.1!

**Comment by Gandalf99** [comment]
10.13.5 is a Developer Beta 1 release. It's not available in the App store nor in the "software update" for us mere mortals. I don't know if a developer beta is even earlier than a public beta, but unless you want to be a guinea pig. . .

**Comment by citovsky** [comment]
i AM a guinea pig. i can let u know what happens under 10.13.5 if u wish just let me know how to do it


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by Gandalf99** [comment]
We continued this conversation off line. Bottom line is that Vitaly tried the Sidebar(Vertical tabs) & it didn't work. Thanks for the update Vitaly.

**Comment by citovsky** [comment]
thank you too


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by anakinsk** [comment]
It is weird but it seems that apple forgets to turn library validation on from time to time, and this is why it is totally possible to use SafariStand without a patcher on 10.13.2-10.13.3. Library validation is back in 10.13.4. I don't have a valid explanation to why is this happening other than apple dev being idiots, and their QA not testing this at all, but who knows there might be a legit reason to this. 

As for the Developer Beta of OS, they might have turned it off specifically for the time the whole thing is in beta so it is easier to dev and debug things?

Safari Stand sidebar issue is described in ticket #75. Closing this for now.
