### ISSUE TITLE
SafariStand sidebar appears to be broken in  Safari 11.1

### ISSUE THREAD

**Issue by attima** [anakinsk/SafariStand#78]
Sorry to reopen this issue but I've just spent ages trying to get SafariStand's sidebar to appear – without success. I have tried multiple times deleting the bundle from MySimbl and then reinstalling it, both with and without the SafariStand patcher. Is there a way around this?

**Comment by anakinsk** [comment]
Hey thanks for reporting this, but it would be a duplicated of issue #75.

Currently there's no workaround, I am investigating and working on a fix. 

Closing as duplicate.

**Comment by attima** [comment]
My apologies, Ivan. I misunderstood. Thanks for your work on SafariStand and fingers crossed you’ll manage to find a fix.

Best wishes

Philip
