### ISSUE TITLE
Not Working on 10.13.4

### ISSUE THREAD

**Issue by drewauff** [anakinsk/SafariStand#81]
It loads only the menubar item and thats it.
Upon loading I get this error message :

Failed to load the SafariStand plugin.
*** -[__NSArrayM objectAtIndexedSubscript:]: index 2 beyond bounds [0 .. 1]

Hope this can be fixed..

**Comment by anakinsk** [comment]
Please install the patcher.

**Comment by drewauff** [comment]
I have tried that but Patcher crashes on launch..

**Comment by drewauff** [comment]
All good now.. seems SIMBL doesn't play nice with Installer..
