### ISSUE TITLE
SafariStand Downgraded Safari Version

### ISSUE THREAD

**Issue by CarterVE** [anakinsk/SafariStand#82]
After installing SafariStand, my Safari version has been downgraded to 10.0.1. I'm not sure if it's actually been downgraded, or if it just thinks it has been, but when visiting certain websites I get a warning about this version not being supported. Is there a way to fix this? Thanks!

**Comment by gharlan** [comment]
https://github.com/anakinsk/SafariStand#macos-sierra-10124-and-library-validation

> This means that even though "About Safari" window shows the older version after applying a patch, you actually still have the latest one.

**Comment by CarterVE** [comment]
Ok great thank you! Just wanted to be sure.

**Comment by almeath** [comment]
Would this only trigger warnings, or could it cause some websites to stop working entirely?
